#!/usr/bin/env python3
"""
Multi-language runtime config generator for xiaozhi-esp32.

Embeds ALL configured languages as a runtime string table, so the device
can switch language at runtime (e.g. first-boot language selection) without
rebuilding. The language passed via --language is the DEFAULT language
(kLanguages[0], used to initialize every inline string before NVS is read).

Sounds are still build-time: only the default language + en-US + common
audio files are embedded (assembly symbols must be unique).
"""
import argparse
import json
import os

# 语言顺序（默认语言在最前）+ 显示名（ASCII 英文，兼容内置 montserrat 字体渲染）
LANGUAGE_ORDER = ["zh-CN", "fil-PH", "vi-VN", "ko-KR", "ms-MY", "en-US"]
DISPLAY_NAMES = {
    "zh-CN": "Chinese",
    "fil-PH": "Filipino",
    "vi-VN": "Vietnamese",
    "ko-KR": "Korean",
    "ms-MY": "Malay",
    "en-US": "English",
}

HEADER_TEMPLATE = """// Auto-generated language config (runtime multi-language)
// Languages: {lang_list}
// Default language: {lang_code} (kLanguages[0])
// Generated by scripts/gen_lang.py — do not edit by hand.
#pragma once

#include <string_view>
#include <cstring>

namespace Lang {{

// 语言元数据（兼容原版 Lang::CODE；跟随运行时语言切换更新）
inline const char* CODE = "{lang_code}";

// ======================= 语言注册表 =======================
struct StringPair {{
    const char* key;
    const char* value;
}};
struct LangMeta {{
    const char* code;          // e.g. "zh-CN"
    const char* display_name;  // 该语言自带名称（用于语言选择界面）
    const StringPair* strings; // 字符串表
    int string_count;
}};

{string_tables}

static constexpr LangMeta kLanguages[] = {{
{lang_metas}
}};

inline constexpr int kLanguageCount = {lang_count};
inline int kCurrentLang = 0;  // 当前语言索引（默认 = 0）

// ---------- 查询 ----------
inline const char* Lookup(const char* key) {{
    const LangMeta& lang = kLanguages[kCurrentLang];
    for (int i = 0; i < lang.string_count; i++) {{
        if (std::strcmp(lang.strings[i].key, key) == 0) return lang.strings[i].value;
    }}
    // fallback: 默认语言（kLanguages[0]）
    for (int i = 0; i < kLanguages[0].string_count; i++) {{
        if (std::strcmp(kLanguages[0].strings[i].key, key) == 0) return kLanguages[0].strings[i].value;
    }}
    return key;
}}
inline const char* LookupDefault(const char* key) {{
    for (int i = 0; i < kLanguages[0].string_count; i++) {{
        if (std::strcmp(kLanguages[0].strings[i].key, key) == 0) return kLanguages[0].strings[i].value;
    }}
    return key;
}}

// ======================= 字符串资源（运行时切换） =======================
namespace Strings {{
{strings}

    // 语言切换后重载全部字符串（inline 变量跨编译单元共享，一次赋值全局生效）
    inline void ReloadAll() {{
{strings_reload}
    }}
}}

// ======================= 语言控制 =======================
inline bool SetLanguage(const char* code) {{
    for (int i = 0; i < kLanguageCount; i++) {{
        if (std::strcmp(kLanguages[i].code, code) == 0) {{
            kCurrentLang = i;
            CODE = kLanguages[i].code;
            Strings::ReloadAll();
            return true;
        }}
    }}
    return false;
}}
inline const char* CurrentCode() {{ return kLanguages[kCurrentLang].code; }}
inline int CurrentIndex() {{ return kCurrentLang; }}
inline int LanguageCount() {{ return kLanguageCount; }}
inline const char* LanguageCode(int index) {{ return kLanguages[index].code; }}
inline const char* LanguageDisplayName(int index) {{ return kLanguages[index].display_name; }}

// ======================= 音效资源（构建期嵌入，仅默认语言+en-US+common） =======================
namespace Sounds {{
{sounds}
}}
}}  // namespace Lang
"""


def load_language_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_base_language(assets_dir):
    """加载 en-US 基准语言数据"""
    base_lang_path = os.path.join(assets_dir, "locales", "en-US", "language.json")
    if os.path.exists(base_lang_path):
        try:
            return load_language_json(base_lang_path)
        except json.JSONDecodeError as e:
            print(f"Warning: Failed to parse en-US language file: {e}")
    else:
        print("Warning: en-US base language file not found, fallback mechanism disabled")
    return {"strings": {}}


def get_sound_files(directory):
    """获取目录中的音效文件列表"""
    if not os.path.exists(directory):
        return []
    return [f for f in os.listdir(directory) if f.endswith(".ogg")]


def esc(v):
    return v.replace('"', '\\"').replace("\\", "\\\\")


def generate_header(lang_code, output_path):
    # 从输出路径推导项目结构
    main_dir = os.path.dirname(output_path)  # main/assets
    if os.path.basename(main_dir) == "assets":
        main_dir = os.path.dirname(main_dir)  # main
    project_dir = os.path.dirname(main_dir)  # 项目根目录
    assets_dir = os.path.join(main_dir, "assets")

    # ---- 校验默认语言 ----
    if lang_code not in LANGUAGE_ORDER:
        raise ValueError(f"Default language {lang_code!r} not in LANGUAGE_ORDER {LANGUAGE_ORDER}")
    # 默认语言排到最前（kLanguages[0]）
    languages = [lang_code] + [c for c in LANGUAGE_ORDER if c != lang_code]

    # ---- 读取并合并每语言字符串 ----
    base_strings = load_base_language(assets_dir).get("strings", {})
    lang_strings = []   # [{code, merged}]
    all_keys = set(base_strings.keys())
    for code in languages:
        input_path = os.path.join(assets_dir, "locales", code, "language.json")
        if not os.path.exists(input_path):
            raise FileNotFoundError(f"Language file not found: {input_path}")
        data = load_language_json(input_path)
        if "language" not in data or "strings" not in data:
            raise ValueError(f"Invalid JSON structure in {input_path}")
        merged = base_strings.copy()
        merged.update(data["strings"])
        lang_strings.append({"code": code, "strings": merged})
        all_keys.update(merged.keys())
        print(f"Language {code}: {len(merged)} strings")

    # 统一键集（全部语言键一致，缺键自动回退 en-US）
    keys = sorted(all_keys)

    # ---- 生成每语言字符串表 ----
    table_parts = []
    meta_parts = []
    for ls in lang_strings:
        sym = ls["code"].replace("-", "_").lower()
        entries = ",\n        ".join(
            '{{"{k}", "{v}"}}'.format(k=k, v=esc(ls["strings"].get(k, base_strings.get(k, k))))
            for k in keys
        )
        table_parts.append(
            f"static constexpr StringPair kStrings_{sym}[] = {{\n"
            f"        {entries}\n    }};"
        )
        display = DISPLAY_NAMES.get(ls["code"], ls["code"])
        meta_parts.append(
            f'    {{"{ls["code"]}", "{display}", kStrings_{sym}, {len(keys)}}},'
        )

    # ---- 生成 Strings inline 变量 + ReloadAll ----
    str_vars = []
    str_reload = []
    for k in keys:
        str_vars.append(f'    inline const char* {k} = Lang::LookupDefault("{k}");')
        str_reload.append(f'        {k} = Lang::Lookup("{k}");')
    strings_block = "\n".join(str_vars)
    strings_reload_block = "\n".join(str_reload)

    # ---- 音效（保持构建期机制：默认语言 + en-US fallback + common） ----
    sounds = []
    current_lang_dir = os.path.join(assets_dir, "locales", lang_code)
    base_lang_dir = os.path.join(assets_dir, "locales", "en-US")
    common_dir = os.path.join(assets_dir, "common")
    base_sounds = get_sound_files(base_lang_dir)
    current_sounds = get_sound_files(current_lang_dir)
    common_sounds = get_sound_files(common_dir)
    all_sound_files = set(base_sounds)
    all_sound_files.update(current_sounds)
    for file in sorted(all_sound_files):
        base_name = os.path.splitext(file)[0]
        sounds.append(f'''
        extern const char ogg_{base_name}_start[] asm("_binary_{base_name}_ogg_start");
        extern const char ogg_{base_name}_end[] asm("_binary_{base_name}_ogg_end");
        static const std::string_view OGG_{base_name.upper()} {{
        static_cast<const char*>(ogg_{base_name}_start),
        static_cast<size_t>(ogg_{base_name}_end - ogg_{base_name}_start)
        }};''')
    for file in sorted(common_sounds):
        base_name = os.path.splitext(file)[0]
        sounds.append(f'''
        extern const char ogg_{base_name}_start[] asm("_binary_{base_name}_ogg_start");
        extern const char ogg_{base_name}_end[] asm("_binary_{base_name}_ogg_end");
        static const std::string_view OGG_{base_name.upper()} {{
        static_cast<const char*>(ogg_{base_name}_start),
        static_cast<size_t>(ogg_{base_name}_end - ogg_{base_name}_start)
        }};''')

    content = HEADER_TEMPLATE.format(
        lang_list=", ".join(languages),
        lang_code=lang_code,
        string_tables="\n\n".join(table_parts),
        lang_metas="\n".join(meta_parts),
        lang_count=len(languages),
        strings=strings_block,
        strings_reload=strings_reload_block,
        sounds="\n".join(sorted(sounds)),
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Successfully generated multi-language config: {output_path}")
    print(f"Languages ({len(languages)}): {', '.join(languages)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate runtime multi-language config header (default language via --language)")
    parser.add_argument("--language", required=True, help="Default language code (e.g. zh-CN, en-US)")
    parser.add_argument("--output", required=True, help="Output header file path")
    args = parser.parse_args()

    try:
        generate_header(args.language, args.output)
    except Exception as e:
        print(f"Error: {e}")
        exit(1)
